### PR TITLE
Add with tabry completion helper

### PR DESCRIPTION
**Pull request by pfgray**
This commit adds a nix helper for binding tabry completion files with
nix packages. The `withTabry` function is a nix function that takes a
tabry completion file and a nix package and returns a derivation that
installs the completion file in the package's completion directory.

example usage:

```nix
wrappedCommand = withTabry ./command.tabry <pkg>
```

### CODE REVIEW

**Comment by pfgray** [comment]
@evanbattaglia , this is ready for some 👀

**Comment by evanbattaglia** [comment]
Thanks for doing this! Sorry I took so long to look at it.  Looks good, the only thing I don't like about it is the fish script is no longer directly runnable, which is nice when developing the script. (The bash script seems to work ok running the template script directly). What do you think about using a template/sentinel value that is  ok to have in the function name, like TABRY_FUNCTION_NAME_PLACEHOLDER (no braces)? Do you see a big disadvantage in that? I guess when developing, it's not a big deal to do a `sed s/{{UNIQ_FN_NAME}}//g tabry-fish.fish | source`, I guess it will probably keep line numbers intact, but it seems like we might as well just keep it runnable directly.

**Comment by pfgray** [comment]
> What do you think about using a template/sentinel value that is ok to have in the function name

Good idea, I'll make that change!

**Comment by evanbattaglia** [comment]
Thanks!

**Pull request merged**
